CREATE TABLE viaje
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    empleado_id   INTEGER                                  NOT NULL,
    carro_id      INTEGER                                  NOT NULL,
    data_retirada date                                     NOT NULL,
    data_entrega  date                                     NOT NULL,
    CONSTRAINT pk_viaje PRIMARY KEY (id)
);

ALTER TABLE viaje
    ADD CONSTRAINT FK_VIAJE_ON_CARRO FOREIGN KEY (carro_id) REFERENCES carro (id);

ALTER TABLE viaje
    ADD CONSTRAINT FK_VIAJE_ON_EMPLEADO FOREIGN KEY (empleado_id) REFERENCES empleado (id);